### ISSUE TITLE
`hungarian` hangs for float weights when there are unassignable jobs

### ISSUE THREAD

**Issue by mastrof** [Gnimuc/Hungarian.jl#18]
I'm observing a weird behavior with the `hungarian` function (tested only on Julia 1.8). If weights are integers the algorithm works fine
```julia
julia> weights_int = [1 missing; missing missing]
2×2 Matrix{Union{Missing, Int64}}:
 1         missing
  missing  missing

julia> hungarian(weights_int)
([1, 0], 1)
```

If the weight matrix has float values instead the algorithm hangs
```julia
julia> weights_float = [1.0 missing; missing missing]
2×2 Matrix{Union{Missing, Float64}}:
 1.0       missing
  missing  missing

julia> hungarian(weights_float)
```

Is this expected behavior? Can it be fixed? How?

**Comment by Gnimuc** [comment]
MWE:
```
weights_int = [1.0 Inf; Inf Inf]
Hungarian.munkres(weights_int)
```

looks like the implementation for forbidden edges hits a corner case.

cc @dourouc05
